name: "similarity app"



on:

  pull_request:

    branches: ["main"]

  workflow_dispatch:



jobs:

  build:

    name: Build workflow

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set up Python

        uses: actions/setup-python@v4

        with:

              python-version: '3.10'

      - name: Install dependencies

        run: |

          python -m pip install --upgrade pip

          pip install -r requirements.txt

      - name: Test with pytest

        run: |

          pip install -r requirements.dev.txt

          pytest test/